name: Elixir CI

on:
  push:
    branches:
      - main # Change this to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.12' # Adjust to your desired Elixir version

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test