name: Elixir CI

on:
  pull_request:
    branches: [ "main", "uat" ]
  push:
    branches: [ "uat" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.15.6'

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test